apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: comparable-olive-snail
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: comparable-olive-snail 
  name: comparable-olive-snail
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: comparable-olive-snail 
